export const CONTENTS = [
    { "id": 1, "title": "폭싹 속았수다", "img_dir": "/images/content/category/slider_item1.jpg", "description": "1950년대 제주에서 태어난 '애순'과 '관식'의 모험 가득한 일생을 사계절로 풀어낸 드라마" },
    { "id": 2, "title": "흑백요리사", "img_dir": "/images/content/category/slider_item2.jpg", "description": "제한 시간 100분 안에 자신의 요리 철학을 담은 단 한 접시의 요리를 만들어내는 요리사들의 대결" },
    { "id": 3, "title": "트리거", "img_dir": "/images/content/category/slider_item3.jpg", "description": "정의감 가득한 방송사 탐사보도팀장과 비밀을 간직한 사회부 기자가 함께 진실을 파헤치는 이야기" },
    { "id": 4, "title": "악연", "img_dir": "/images/content/category/slider_item4.jpg", "description": "벗어나려 해도 끝없이 얽히는 세 사람의 지독한 악연을 그린 범죄 스릴러" },
    { "id": 5, "title": "수리남", "img_dir": "/images/content/category/slider_item5.jpg", "description": "남미 국가 수리남을 장악한 마약 대부로 인해 누명을 쓴 한 민간인이 국정원의 비밀 임무를 수락하며 벌어지는 이야기" },
    { "id": 6, "title": "광장", "img_dir": "/images/content/category/slider_item6.jpg", "description": "스스로 아킬레스건을 자르고 조직을 떠났던 남자가 동생의 죽음 뒤에 숨겨진 비밀을 파헤치는 누아르" },
    { "id": 7, "title": "돌싱글즈", "img_dir": "/images/content/category/slider_item7.webp", "description": "한번 다녀온 돌싱 남녀들의 연애부터 동거까지, 새로운 인연을 찾아 나서는 리얼리티 쇼" },
    { "id": 8, "title": "탐정들의 영업비밀", "img_dir": "/images/content/category/slider_item8.webp", "description": "생활 밀착형 탐정들의 실제 사건 사고를 따라가는 리얼리티 프로그램" },
    { "id": 9, "title": "용감한 형사들", "img_dir": "/images/content/category/slider_item11.webp", "description": "실제 형사들이 직접 출연하여 경험했던 충격적인 범죄 사건들의 수사 일지를 파헤치는 프로그램" },
    { "id": 10, "title": "그것이 알고싶다", "img_dir": "/images/content/category/slider_item12.webp", "description": "사회, 정치, 미제 사건 등 다양한 분야의 미스터리를 추적하고 진실을 파헤치는 시사 교양 프로그램" },
    { "id": 11, "title": "소년심판", "img_dir": "/images/content/category/slider_item14.jpg", "description": "소년범을 혐오하는 판사가 한 지방법원 소년부에 부임하면서 마주하게 되는 소년범죄와 그들을 둘러싼 이야기" },
    { "id": 12, "title": "비밀의 숲", "img_dir": "/images/content/category/slider_item16.webp", "description": "감정을 느끼지 못하는 검사가 한 형사와 함께 검찰 스폰서 살인사건과 그 이면에 숨겨진 진실을 추적하는 스릴러" },
    { "id": 13, "title": "브레이킹 배드", "img_dir": "/images/content/category/slider_item18.webp", "description": "폐암 말기 판정을 받은 한 화학 교사가 가족의 미래를 위해 마약 제조에 뛰어들며 벌어지는 이야기" },
    { "id": 14, "title": "작은 아씨들", "img_dir": "/images/content/category/slider_item19.webp", "description": "가난하지만 우애 있게 자란 세 자매가 대한민국에서 가장 부유하고 유력한 가문에 맞서는 이야기" },
    { "id": 15, "title": "더 글로리", "img_dir": "/images/content/category/slider_item20.jpg", "description": "유년 시절 폭력으로 영혼까지 부서진 한 여자가 온 생을 걸어 치밀하게 준비한 처절한 복수극" },
    { "id": 16, "title": "나의 해방일지", "img_dir": "/images/content/category/slider_item21.webp", "description": "견딜 수 없이 촌스러운 삼 남매의 견딜 수 없이 사랑스러운 행복 소생기를 그린 드라마" },
    { "id": 17, "title": "시그널", "img_dir": "/images/content/category/slider_item22.webp", "description": "과거로부터 걸려온 간절한 신호로 연결된 현재와 과거의 형사들이 미제 사건들을 다시 파헤치는 이야기" },
    { "id": 18, "title": "펜트하우스", "img_dir": "/images/content/category/slider_item23.webp", "description": "100층 펜트하우스의 범접불가 '퀸'과 모든 것을 집어삼키는 욕망의 '프리마돈나'가 벌이는 부동산과 교육 전쟁" },
    { "id": 19, "title": "연인", "img_dir": "/images/content/category/slider_item24.webp", "description": "병자호란을 겪으며 엇갈리는 연인들의 사랑과 백성들의 생명력을 다룬 휴먼역사멜로드라마" },
    { "id": 20, "title": "오징어 게임", "img_dir": "/images/hero/poster.webp", "description": "456억 원의 상금이 걸린 의문의 서바이벌에 참가한 사람들이 최후의 승자가 되기 위해 목숨을 걸고 극한의 게임에 도전하는 이야기" },
    { "id": 21, "title": "살인자ㅇ난감", "img_dir": "/images/content/rank/rank1_inner.jpg", "description": "우연히 살인을 시작하게 된 평범한 남자와 그를 지독하게 쫓는 형사의 이야기" },
    { "id": 22, "title": "폭군", "img_dir": "/images/content/rank/rank2_inner.jpg", "description": "폭군 프로그램의 마지막 샘플이 배달 사고로 사라진 후, 각기 다른 목적을 가진 사람들이 이를 차지하기 위해 모여드는 추격 액션물" },
    { "id": 23, "title": "에스콰이어", "img_dir": "/images/content/rank/rank3_inner.jpg", "description": "세상 물정 모르는 신입 변호사가 실력은 최고지만 냉소적인 파트너 변호사를 만나 성장하는 오피스 드라마" },
    { "id": 24, "title": "엠마", "img_dir": "/images/content/rank/rank4_inner.jpg", "description": "자신을 비난하던 상사를 납치한 남자가 그녀가 사실 외계인이라고 믿게 되면서 벌어지는 코미디 스릴러" },
    { "id": 25, "title": "귀멸의 칼날", "img_dir": "/images/content/rank/rank5_inner.jpg", "description": "혈귀로 변해버린 여동생을 인간으로 되돌리기 위해 소년이 혈귀들과 맞서 싸우는 이야기" },
    { "id": 26, "title": "웬즈데이", "img_dir": "/images/content/rank/rank6_inner.jpg", "description": "아담스 패밀리의 딸 웬즈데이가 네버모어 아카데미에 입학해 연쇄 살인 사건을 조사하며 벌어지는 이야기" },
    { "id": 27, "title": "은중과 상연", "img_dir": "/images/content/rank/rank7_inner.jpg", "description": "오랜 시간 절친이었던 두 사람이 한 남자를 사이에 두고 벌이는 격렬한 싸움과 재회를 그린 드라마" },
    { "id": 28, "title": "나는 SOLO", "img_dir": "/images/content/rank/rank8_inner.jpg", "description": "결혼을 간절히 원하는 솔로 남녀들이 모여 사랑을 찾기 위해 고군분투하는 극사실주의 데이팅 프로그램" },
    { "id": 29, "title": "잠들 수 없는 하루", "img_dir": "/images/content/rank/rank9_inner.jpg", "description": "갑작스러운 비극으로 모든 것을 잃은 여자가 한 남자를 만나 구원받고 성장하는 이야기" },
    { "id": 30, "title": "마이틴", "img_dir": "/images/content/rank/rank10_inner.jpg", "description": "평범한 소녀가 우연히 K-POP 아이돌이 되면서 겪는 꿈과 사랑, 그리고 우정을 그린 하이틴 드라마" },
    { "id": 31, "title": "도시의 그림자", "img_dir": "/images/content/category/slider_item1.jpg", "description": "밤의 도시를 배경으로, 부패한 권력에 맞서는 고독한 해결사의 이야기." },
    { "id": 32, "title": "시간의 경계", "img_dir": "/images/content/category/slider_item2.jpg", "description": "시간 여행의 비밀을 발견한 물리학자가 과거를 바꾸려다 예상치 못한 결과에 직면한다." },
    { "id": 33, "title": "마지막 왕조", "img_dir": "/images/content/category/slider_item3.jpg", "description": "몰락해가는 왕조의 마지막 왕세자가 나라를 구하기 위해 자신의 모든 것을 거는 사투." },
    { "id": 34, "title": "코드네임: 제로", "img_dir": "/images/content/category/slider_item4.jpg", "description": "기억을 잃은 비밀 요원이 자신의 정체성과 거대한 음모의 실체를 추적하는 첩보 액션." },
    { "id": 35, "title": "심해의 노래", "img_dir": "/images/content/category/slider_item5.jpg", "description": "전설 속 바다 생물을 찾아 나선 해양 생물학자가 심해에서 미지의 문명을 발견한다." },
    { "id": 36, "title": "골든 레시피", "img_dir": "/images/content/category/slider_item6.jpg", "description": "최고의 셰프가 되기 위해 전국의 숨은 맛집을 찾아다니는 청년의 유쾌한 성장 드라마." },
    { "id": 37, "title": "유령 작가", "img_dir": "/images/content/category/slider_item7.webp", "description": "타인의 삶을 대신 살아주는 유령 작가가 한 재벌의 자서전을 쓰면서 위험한 진실에 다가선다." },
    { "id": 38, "title": "리셋 증후군", "img_dir": "/images/content/category/slider_item8.webp", "description": "하루의 기억이 매일 리셋되는 남자, 그의 곁을 지키는 여자와의 애틋한 사랑 이야기." },
    { "id": 39, "title": "왕관의 무게", "img_dir": "/images/content/rank/rank1_inner.jpg", "description": "왕의 자리를 놓고 벌어지는 형제들의 치열한 암투와 배신, 그리고 사랑을 그린 시대극." },
    { "id": 40, "title": "아파트: 비상구 없음", "img_dir": "/images/content/rank/rank2_inner.jpg", "description": "의문의 바이러스로 봉쇄된 아파트, 생존을 위한 주민들의 극한 사투가 시작된다." },
    { "id": 41, "title": "퍼펙트 게임", "img_dir": "/images/content/rank/rank3_inner.jpg", "description": "한물간 프로게이머가 신인들을 이끌고 E-스포츠 리그의 정상에 도전하는 감동 스토리." },
    { "id": 42, "title": "인공의 봄", "img_dir": "/images/content/rank/rank4_inner.jpg", "description": "인간의 감정을 학습한 AI 로봇과 사랑에 빠진 한 남자의 이야기." },
    { "id": 43, "title": "괴물 사냥꾼", "img_dir": "/images/content/rank/rank5_inner.jpg", "description": "현대 서울에 나타난 괴물들을 사냥하는 비밀 조직 '헌터'들의 활약을 그린 판타지 액션." },
    { "id": 44, "title": "타임리스 호텔", "img_dir": "/images/content/rank/rank6_inner.jpg", "description": "시간이 멈춘 호텔에서 영원히 늙지 않는 사람들과 그곳에 갇힌 한 남자의 미스터리." },
    { "id": 45, "title": "변호의 기술", "img_dir": "/images/content/rank/rank7_inner.jpg", "description": "패배를 모르는 냉혈 변호사가 한 사건을 계기로 진정한 정의의 의미를 깨닫게 된다." },
    { "id": 46, "title": "우리 이혼했어요", "img_dir": "/images/content/rank/rank8_inner.jpg", "description": "이혼한 부부들이 다시 만나 한 집에서 생활하며 서로를 이해해가는 과정을 담은 리얼리티." },
    { "id": 47, "title": "서울의 밤", "img_dir": "/images/content/category/slider_item11.webp", "description": "화려한 서울의 밤을 배경으로, 각자의 꿈과 상처를 안고 살아가는 청춘들의 이야기." },
    { "id": 48, "title": "절대 권력", "img_dir": "/images/content/category/slider_item12.webp", "description": "대통령을 만들기 위해 모든 것을 거는 정치 컨설턴트들의 치열한 두뇌 싸움." },
    { "id": 49, "title": "사라진 아이들", "img_dir": "/images/content/category/slider_item14.jpg", "description": "한 마을에서 아이들이 연이어 사라지자, 사건을 파헤치는 형사와 마을 주민들의 의심과 갈등." },
    { "id": 50, "title": "블랙홀", "img_dir": "/images/content/category/slider_item16.webp", "description": "서울 상공에 나타난 의문의 블랙홀, 그 안으로 빨려 들어간 사람들의 생존 사투." },
    { "id": 51, "title": "황금 제국", "img_dir": "/images/content/category/slider_item18.webp", "description": "대한민국 경제를 뒤흔들었던 한 재벌 가문의 욕망과 암투를 그린 대서사시." },
    { "id": 52, "title": "너의 목소리", "img_dir": "/images/content/category/slider_item19.webp", "description": "다른 사람의 마음의 소리를 들을 수 있는 능력을 가진 남자와 그의 비밀을 아는 여자의 로맨스." },
    { "id": 53, "title": "최고의 식탁", "img_dir": "/images/content/category/slider_item20.jpg", "description": "전국의 숨겨진 요리 고수들이 모여 단 하나의 '최고의 식탁'을 차리기 위해 경쟁한다." },
    { "id": 54, "title": "해방촌 블루스", "img_dir": "/images/content/category/slider_item21.webp", "description": "오래된 동네 해방촌에 모여든 다양한 사람들의 소소하지만 따뜻한 일상과 사랑." },
    { "id": 55, "title": "과거를 묻는 소년", "img_dir": "/images/content/category/slider_item22.webp", "description": "20년 전 미제 사건의 유일한 목격자였던 소년이 형사가 되어 다시 사건을 마주한다." },
    { "id": 56, "title": "욕망의 계절", "img_dir": "/images/content/category/slider_item23.webp", "description": "모든 것을 가졌지만 만족하지 못하는 상류층 사람들의 위선과 끝없는 욕망을 그린 드라마." },
    { "id": 57, "title": "가을의 연가", "img_dir": "/images/content/category/slider_item24.webp", "description": "가을의 정취가 물씬 풍기는 작은 시골 마을에서 펼쳐지는 두 남녀의 운명적인 사랑." },
    { "id": 58, "title": "지옥의 변호사", "img_dir": "/images/content/rank/rank9_inner.jpg", "description": "악마 같은 변호사가 진짜 악마들을 만나 그들을 지옥으로 보내기 위해 싸우는 판타지 법정 드라마." },
    { "id": 59, "title": "별에서 온 셰프", "img_dir": "/images/content/rank/rank10_inner.jpg", "description": "자신의 행성으로 돌아가야 하는 외계인 셰프가 지구에서의 마지막 레스토랑을 연다." },
    { "id": 60, "title": "조선 좀비뎐", "img_dir": "/images/hero/poster.webp", "description": "왕이 좀비로 변해버린 조선, 왕세자가 반란 세력과 좀비 떼에 맞서 나라를 구하는 액션 스릴러." },
    { "id": 61, "title": "Echoes of Tomorrow", "img_dir": "/images/content/category/slider_item1.jpg", "description": "A scientist discovers a way to receive messages from the future, only to learn of an impending apocalypse." },
    { "id": 62, "title": "The Crimson Blade", "img_dir": "/images/content/category/slider_item2.jpg", "description": "In a realm of fantasy, a disgraced knight seeks redemption by hunting down a legendary cursed sword." },
    { "id": 63, "title": "Zero Point", "img_dir": "/images/content/category/slider_item3.jpg", "description": "A team of elite soldiers is sent on a mission to a parallel universe from which no one has ever returned." },
    { "id": 64, "title": "City of Whispers", "img_dir": "/images/content/category/slider_item4.jpg", "description": "A private detective in a rain-soaked city uncovers a political conspiracy that goes deeper than any case he's ever handled." },
    { "id": 65, "title": "Starlight Odyssey", "img_dir": "/images/content/category/slider_item5.jpg", "description": "The last remnants of humanity travel across the galaxy in a giant ark, searching for a new home." },
    { "id": 66, "title": "The Gilded Cage", "img_dir": "/images/content/category/slider_item6.jpg", "description": "A story of love, betrayal, and power within the high society of 1920s New York." },
    { "id": 67, "title": "Masters of the Kitchen", "img_dir": "/images/content/category/slider_item7.webp", "description": "World-renowned chefs compete in a high-stakes culinary battle to be crowned the ultimate food champion." },
    { "id": 68, "title": "The Alchemist's Secret", "img_dir": "/images/content/category/slider_item8.webp", "description": "A historian stumbles upon an ancient manuscript that could lead to the legendary Philosopher's Stone." },
    { "id": 69, "title": "Cybernetic Dawn", "img_dir": "/images/content/rank/rank1_inner.jpg", "description": "In a futuristic city, a detective who is half-human, half-machine hunts a rogue AI threatening to dismantle society." },
    { "id": 70, "title": "Forgotten Kingdom", "img_dir": "/images/content/rank/rank2_inner.jpg", "description": "An archaeologist discovers a map leading to a mythical lost kingdom, but a shadowy organization wants to get there first." },
    { "id": 71, "title": "The Last Stand", "img_dir": "/images/content/rank/rank3_inner.jpg", "description": "A small town sheriff must defend his home against a ruthless gang of outlaws in this modern western." },
    { "id": 72, "title": "Project Chimera", "img_dir": "/images/content/rank/rank4_inner.jpg", "description": "A genetics experiment goes wrong, and a team of scientists must hunt down the creature they created." },
    { "id": 73, "title": "Heir of the Dragon", "img_dir": "/images/content/rank/rank5_inner.jpg", "description": "A young orphan discovers she is the last descendant of a long line of dragon riders and must unite with a dragon to save her world." },
    { "id": 74, "title": "Midnight Club", "img_dir": "/images/content/rank/rank6_inner.jpg", "description": "Illegal street racers risk it all for fame and fortune in the neon-lit nights of Tokyo." },
    { "id": 75, "title": "The Diplomat", "img_dir": "/images/content/rank/rank7_inner.jpg", "description": "A seasoned ambassador is thrown into a geopolitical crisis when she is appointed to a new, high-stakes post." },
    { "id": 76, "title": "Love in Bloom", "img_dir": "/images/content/rank/rank8_inner.jpg", "description": "A cynical florist and a cheerful baker find that opposites attract in this heartwarming romantic comedy." },
    { "id": 77, "title": "The Silent Witness", "img_dir": "/images/content/category/slider_item11.webp", "description": "A murder in a soundproof room. The only witness is a parrot. A detective must solve the seemingly impossible crime." },
    { "id": 78, "title": "Vanguard", "img_dir": "/images/content/category/slider_item12.webp", "description": "A team of superheroes, long since disbanded, must reunite to face a cosmic threat they thought they had defeated." },
    { "id": 79, "title": "The Inheritance", "img_dir": "/images/content/category/slider_item14.jpg", "description": "After a wealthy patriarch's death, his family gathers for the will reading, only to find themselves trapped in a deadly game." },
    { "id": 80, "title": "Quantum Leap", "img_dir": "/images/content/category/slider_item16.webp", "description": "A physicist testing a time-travel theory finds himself leaping into the bodies of different people throughout history." },
    { "id": 81, "title": "The Outsider", "img_dir": "/images/content/category/slider_item18.webp", "description": "An investigation into a gruesome murder is complicated by a supernatural force." },
    { "id": 82, "title": "Siren's Call", "img_dir": "/images/content/category/slider_item19.webp", "description": "Fishermen in a small coastal town begin to disappear after hearing a mysterious, enchanting song from the sea." },
    { "id": 83, "title": "The Grandmaster", "img_dir": "/images/content/category/slider_item20.jpg", "description": "The life story of the legendary martial artist who trained a generation of masters." },
    { "id": 84, "title": "Blue Sky Cafe", "img_dir": "/images/content/category/slider_item21.webp", "description": "A small-town cafe becomes the center of its community's lives, loves, and losses." },
    { "id": 85, "title": "The Conductor", "img_dir": "/images/content/category/slider_item22.webp", "description": "A world-famous orchestra conductor with a dark past finds his life unraveling when a figure from his youth reappears." },
    { "id": 86, "title": "House of Cards", "img_dir": "/images/content/category/slider_item23.webp", "description": "A ruthless congressman will stop at nothing to conquer the halls of power in Washington D.C." },
    { "id": 87, "title": "The Crown", "img_dir": "/images/content/category/slider_item24.webp", "description": "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century." },
    { "id": 88, "title": "Mind Hunter", "img_dir": "/images/content/rank/rank9_inner.jpg", "description": "In the late 1970s, two FBI agents expand criminal science by delving into the psychology of murder." },
    { "id": 89, "title": "The Chef's Table", "img_dir": "/images/content/rank/rank10_inner.jpg", "description": "A docu-series that profiles the world's most renowned chefs, exploring their philosophies and culinary styles." },
    { "id": 90, "title": "Stranger Things", "img_dir": "/images/hero/poster.webp", "description": "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl." },
    { "id": 91, "title": "Narcos", "img_dir": "/images/content/category/slider_item5.jpg", "description": "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years." },
    { "id": 92, "title": "Black Mirror", "img_dir": "/images/content/category/slider_item4.jpg", "description": "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide." },
    { "id": 93, "title": "Ozark", "img_dir": "/images/content/category/slider_item16.webp", "description": "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss." },
    { "id": 94, "title": "The Witcher", "img_dir": "/images/content/rank/rank2_inner.jpg", "description": "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts." },
    { "id": 95, "title": "Peaky Blinders", "img_dir": "/images/content/category/slider_item6.jpg", "description": "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby." },
    { "id": 96, "title": "Money Heist", "img_dir": "/images/content/rank/rank3_inner.jpg", "description": "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain." },
    { "id": 97, "title": "Dark", "img_dir": "/images/content/category/slider_item1.jpg", "description": "A family saga with a supernatural twist, set in a German town, where the disappearance of two young children exposes the relationships among four families." },
    { "id": 98, "title": "The Queen's Gambit", "img_dir": "/images/content/rank/rank7_inner.jpg", "description": "Orphaned chess prodigy Beth Harmon struggles with addiction in a quest to become the greatest chess player in the world." },
    { "id": 99, "title": "Cobra Kai", "img_dir": "/images/content/category/slider_item9.webp", "description": "Decades after their 1984 All Valley Karate Tournament bout, a middle-aged Daniel LaRusso and Johnny Lawrence find themselves martial-arts rivals again." },
    { "id": 100, "title": "Lupin", "img_dir": "/images/content/rank/rank9_inner.jpg", "description": "Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family." }
];